name = "fyl-api"
main = "index.js"
compatibility_date = "2026-05-01"

[[d1_databases]]
binding = "DB"
database_name = "fyl-articles"
# `npx wrangler d1 create fyl-articles` の出力で置き換える
database_id = "059349fc-d32a-4422-93de-af77b7a7317f"

[triggers]
crons = ["0 * * * *"]
